{{ config(materialized='incremental', incremental_strategy='merge',
          unique_key=['location_id', 'observed_at']) }}
-- Intentionally scan all committed RAW rows. Observation-time watermarks lose historical backfills.
-- Full-source merge also applies corrections loaded at any time; optimize only with a durable load cursor.
select location_id, observed_at,
    temperature_2m,
    relative_humidity_2m,
    dew_point_2m,
    apparent_temperature,
    precipitation,
    rain,
    snowfall,
    snow_depth,
    weather_code,
    pressure_msl,
    surface_pressure,
    cloud_cover,
    cloud_cover_low,
    cloud_cover_mid,
    cloud_cover_high,
    et0_fao_evapotranspiration,
    vapour_pressure_deficit,
    wind_speed_10m,
    wind_speed_100m,
    wind_direction_10m,
    wind_direction_100m,
    wind_gusts_10m,
    soil_temperature_0_to_7cm,
    soil_temperature_7_to_28cm,
    soil_temperature_28_to_100cm,
    soil_temperature_100_to_255cm,
    soil_moisture_0_to_7cm,
    soil_moisture_7_to_28cm,
    soil_moisture_28_to_100cm,
    soil_moisture_100_to_255cm,
    boundary_layer_height,
    wet_bulb_temperature_2m,
    total_column_integrated_water_vapour,
    is_day,
    sunshine_duration,
    shortwave_radiation,
    direct_radiation,
    diffuse_radiation,
    direct_normal_irradiance,
    global_tilted_irradiance,
    terrestrial_radiation,
    shortwave_radiation_instant,
    direct_radiation_instant,
    diffuse_radiation_instant,
    direct_normal_irradiance_instant,
    global_tilted_irradiance_instant,
    terrestrial_radiation_instant,
    loaded_at, source_file, source_row_number, source_checksum
from {{ source('weather_raw', 'weather_hourly') }}
qualify row_number() over(partition by location_id, observed_at
    order by loaded_at desc, source_file desc, source_row_number desc) = 1
